### PR TITLE
tool/agent: Implement deduplication for graph completion snapshots in Tool's response handling

### LINKED ISSUE #1640: AgentTool may duplicate final content in callable mode (collectLegacyResponse concatenates repeated assistant events)
**Describe the bug**
When an Agent is used as a Tool (e.g. team member tool), the tool result may contain duplicated final content, such as two concatenated JSON objects:

{"doc_id":"LyNg_QFTEX","title":"To C...PRD模板"}{"doc_id":"LyNg_QFTEX","title":"To C...PRD模板"}

This breaks strict JSON parsing in downstream systems.

**To Reproduce**
1. Create a team with a main agent and a sub-agent exposed as member tool.
2. Let the sub-agent output a strict one-line JSON string as final answer.
3. Invoke the member tool from the main agent.
4. Observe that tool `Result` may contain duplicated final content (`{...}{...}`).

Observed in logs (`AfterTool`):
- `ToolName`: `team-members-smart-import-main-agent_generate-sub-agent`
- `Result`: `{"doc_id":"...","title":"..."}{"doc_id":"...","title":"..."}`

**Expected behavior**
Tool result should contain exactly one final assistant output (single valid JSON object), not concatenated duplicates.

**Screenshots**
N/A (log-based reproduction)

**Environment (please complete the following information):**
 - OS: macOS (darwin/arm64) for development; also observed in Linux container runtime
 - Version: trpc-agent-go `v1.8.1`
 - Go version: `go1.26.0`
 - tRPC-A2A-go version: `v0.2.5`

**Additional context**
Potential root cause appears in `tool/agent/agent_tool.go`:

- `collectResponse` falls back to `collectLegacyResponse` when `!shouldRewriteCallableCompletion(inv)`:
  - around line ~679-682
- `collectLegacyResponse` appends every assistant event content directly:
  - around line ~722-735

If the event stream includes both a non-partial final content event and another completion/final snapshot with the same content, both are concatenated, producing duplicated output.

Suggestion:
- In legacy collection path, deduplicate terminal assistant content (e.g. by response/event id or content + completion boundary), or prefer last non-partial assistant message instead of concatenating all assistant messages.
- Add a regression test where two assistant events carry identical final content and verify tool result is emitted once.

### PR DESCRIPTION
**Pull request by liuzengh**
close  #1640

### CODE REVIEW

File: tool/agent/agent_tool.go [hunk 1]
```diff
@@ -719,17 +719,36 @@ func (at *Tool) collectResponse(inv *agent.Invocation, evCh <-chan *event.Event)
...
+			continue
+		}
+		choice := ev.Response.Choices[0]
+		if choice.Message.Role != model.RoleAssistant || choice.Message.Content == "" {
+			continue
+		}
+		content := choice.Message.Content
+		if !ev.IsPartial &&
+			isGraphCompletionSnapshotEvent(ev) &&
+			content == lastNonPartialAssistantContent {
```
Comment (Flash-LHR) [inline tool/agent/agent_tool.go:746]: This drops a real terminal response when `last_response_id` changes but the text stays the same. Please compare `graph.StateKeyLastResponseID` first and only skip when the IDs match.
<details><summary>中文</summary>
当 `last_response_id` 变化但文本相同时，这里会丢掉真实的终态响应。请先比较 `graph.StateKeyLastResponseID`，只有 ID 一致时才跳过。
</details>

**Review by sandyskies — APPROVED** [review]
LGTM
